# Generated by Django 4.2.4 on 2023-08-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copper', models.IntegerField(verbose_name='Медь, цена:')),
                ('aluminum', models.IntegerField(verbose_name='Алюминий, цена:')),
                ('brass', models.IntegerField(verbose_name='Латунь, цена:')),
                ('tin', models.IntegerField(verbose_name='Олово, цена:')),
                ('nickel', models.IntegerField(verbose_name='Никель, цена:')),
                ('zink', models.IntegerField(verbose_name='Цинк, цена:')),
                ('steel', models.IntegerField(verbose_name='Сталь, цена:')),
                ('сast_iron', models.IntegerField(verbose_name='Чугун, цена:')),
                ('iron', models.IntegerField(verbose_name='Железо, цена:')),
            ],
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
