# Generated by Django 4.2.4 on 2023-08-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_prices_alter_application_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prices',
            options={'verbose_name': 'Цена', 'verbose_name_plural': 'Цены'},
        ),
        migrations.RemoveField(
            model_name='prices',
            name='aluminum',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='brass',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='copper',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='iron',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='nickel',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='steel',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='tin',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='zink',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='сast_iron',
        ),
        migrations.AddField(
            model_name='prices',
            name='metal',
            field=models.CharField(default='Неизвестный металл', max_length=20, verbose_name='Металл'),
        ),
        migrations.AddField(
            model_name='prices',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
