# Generated by Django 4.2.4 on 2023-08-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_prices_metal_alter_prices_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
    ]
